Cleanup and Docstrings
TitaniumTigers4829/offseason-robot-code-2024 pull request #47
Opened 2024-10-17 18:51 UTC by aridavidson001

mostly formatting stuff but also a tiny thing in the pivot subsystem

2024-10-17 18:57 UTC, Ishan1522 requested changes
very much not clean 👎

2024-10-17 18:57 UTC, Ishan1522 commented on src/main/java/frc/robot/subsystems/indexer/Indexer.java
> +   * @param speed
capitalize ur docstrings, include bounds of speed, and units

2024-10-17 18:57 UTC, Ishan1522 commented on src/main/java/frc/robot/subsystems/intake/Intake.java
>    public void setPivotAngle(double angle) {
id add a conversion from degrees to rotations here to make it easier to tune. Also capitilize stuff

2024-10-17 18:57 UTC, Ishan1522 commented on src/main/java/frc/robot/subsystems/intake/Intake.java
> +   * @param speed sets the intake roller speed in rotations/sec
it is a dutycycle output (unitless) from -1 to 1

2024-10-17 18:57 UTC, Ishan1522 commented on src/main/java/frc/robot/subsystems/swerve/SwerveDrive.java
> +   * @param ySpeed
if ur gonna write a docstring, add the docs.

2024-10-17 18:57 UTC, Ishan1522 commented on src/main/java/frc/robot/subsystems/swerve/SwerveDrive.java
> +   * runs characterization based on volts
capitalize stuff

2024-10-17 23:44 UTC, Ishan1522 requested changes

2024-10-17 23:44 UTC, Ishan1522 commented on src/main/java/frc/robot/subsystems/intake/Intake.java
> +    double angleRots = angle / 360;
Just do 
`Units.rotationsToDegrees()`

2024-10-18 13:58 UTC, aridavidson001 commented
the check format java thing works when I run it in the terminal, idk why it isn't working here @Ishan1522

2024-10-18 14:22 UTC, Ishan1522 commented
i fixed it @aridavidson001

2024-10-18 14:46 UTC, merged